export enum EXCEPTION_CODE {
  AUTHENTICATION_FAILED = 1001, // 未授权
  PARAMETER_ERROR = 1002, // 参数有误
  NO_PERMISSION = 1003, // 没有操作权限
  SYSTEM_CONFIG_ERROR = 1004, // 系统配置错误

  USER_EXISTS = 2001, // 用户已存在
  USER_NOT_EXISTS = 2002, // 用户不存在
  USER_PASSWORD_WRONG = 2003, // 用户名或密码错误
  PASSWORD_INVALID = 2004, // 密码无效
  NO_SURVEY_PERMISSION = 3001, // 没有问卷权限
  SURVEY_STATUS_TRANSFORM_ERROR = 3002, // 问卷状态转换报错
  SURVEY_TYPE_ERROR = 3003, // 问卷类型错误
  SURVEY_NOT_FOUND = 3004, // 问卷不存在
  SURVEY_CONTENT_NOT_ALLOW = 3005, // 存在禁用内容
  SURVEY_SAVE_CONFLICT = 3006, // 问卷冲突
  CAPTCHA_INCORRECT = 4001, // 验证码不正确
  WHITELIST_ERROR = 4002, // 白名单校验错误

  RESPONSE_SIGN_ERROR = 9001, // 签名不正确
  RESPONSE_CURRENT_TIME_NOT_ALLOW = 9002, // 当前时间不允许提交
  RESPONSE_OVER_LIMIT = 9003, // 超出限制
  RESPONSE_SCHEMA_REMOVED = 9004, // 问卷已删除
  RESPONSE_DATA_DECRYPT_ERROR = 9005, // 问卷已删除
  RESPONSE_PAUSING = 9006, // 问卷已暂停

  UPLOAD_FILE_ERROR = 5001, // 上传文件错误
  SERVER_ERROR = 5002, // 获取数据失败
}
