# Lint
name: Server Lint

on:
  push:
    branches:
      - main
      - releases/**
    paths:
      - server/**
  pull_request:
    branches:
      - develop
      - main
      - releases/**
      - feature/**
    paths:
      - server/**
  workflow_dispatch:

jobs:
  build:
    name: Lint
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        run: cd server && npm install

      - name: Lint
        run: cd server && npm run lint

      - name: Format
        run: cd server && npm run format
