/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    ElButton: typeof import('element-plus/es')['ElButton']
    ElCheckbox: typeof import('element-plus/es')['ElCheckbox']
    ElCollapse: typeof import('element-plus/es')['ElCollapse']
    ElCollapseItem: typeof import('element-plus/es')['ElCollapseItem']
    ElColorPicker: typeof import('element-plus/es')['ElColorPicker']
    ElDatePicker: typeof import('element-plus/es')['ElDatePicker']
    ElDialog: typeof import('element-plus/es')['ElDialog']
    ElForm: typeof import('element-plus/es')['ElForm']
    ElFormItem: typeof import('element-plus/es')['ElFormItem']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElInputNumber: typeof import('element-plus/es')['ElInputNumber']
    ElOption: typeof import('element-plus/es')['ElOption']
    ElPagination: typeof import('element-plus/es')['ElPagination']
    ElPopover: typeof import('element-plus/es')['ElPopover']
    ElRadio: typeof import('element-plus/es')['ElRadio']
    ElRadioButton: typeof import('element-plus/es')['ElRadioButton']
    ElRadioGroup: typeof import('element-plus/es')['ElRadioGroup']
    ElRow: typeof import('element-plus/es')['ElRow']
    ElSelect: typeof import('element-plus/es')['ElSelect']
    ElSlider: typeof import('element-plus/es')['ElSlider']
    ElSwitch: typeof import('element-plus/es')['ElSwitch']
    ElTable: typeof import('element-plus/es')['ElTable']
    ElTableColumn: typeof import('element-plus/es')['ElTableColumn']
    ElTabPane: typeof import('element-plus/es')['ElTabPane']
    ElTabs: typeof import('element-plus/es')['ElTabs']
    ElTag: typeof import('element-plus/es')['ElTag']
    ElTimePicker: typeof import('element-plus/es')['ElTimePicker']
    ElTooltip: typeof import('element-plus/es')['ElTooltip']
    IEpBottom: typeof import('~icons/ep/bottom')['default']
    IEpCheck: typeof import('~icons/ep/check')['default']
    IEpCirclePlus: typeof import('~icons/ep/circle-plus')['default']
    IEpClose: typeof import('~icons/ep/close')['default']
    IEpCopyDocument: typeof import('~icons/ep/copy-document')['default']
    IEpDelete: typeof import('~icons/ep/delete')['default']
    IEpLoading: typeof import('~icons/ep/loading')['default']
    IEpMinus: typeof import('~icons/ep/minus')['default']
    IEpPlus: typeof import('~icons/ep/plus')['default']
    IEpQuestionFilled: typeof import('~icons/ep/question-filled')['default']
    IEpRank: typeof import('~icons/ep/rank')['default']
    IEpRankMinus: typeof import('~icons/ep/rank-minus')['default']
    IEpRemove: typeof import('~icons/ep/remove')['default']
    IEpSearch: typeof import('~icons/ep/search')['default']
    IEpSort: typeof import('~icons/ep/sort')['default']
    IEpSortDown: typeof import('~icons/ep/sort-down')['default']
    IEpSortUp: typeof import('~icons/ep/sort-up')['default']
    IEpTop: typeof import('~icons/ep/top')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
  export interface ComponentCustomProperties {
    vLoading: typeof import('element-plus/es')['ElLoadingDirective']
  }
}
